"""Notes rendering, which is pure, and the staged write the front ends use."""

import pytest

from ipynb_scrubber.exceptions import ScrubberError
from ipynb_scrubber.notes import render_notes, require_destination
from ipynb_scrubber.staging import commit_all, stage


def write(path, content):
    """Stage and commit one file, which is what both front ends do to notes."""
    commit_all([stage(path, content)])


def test_content_is_fenced_as_python_by_default():
    content = render_notes({'ex-1': 'SOLUTION = 1'})

    assert '## ex-1' in content
    assert '```python\nSOLUTION = 1\n```' in content
    assert content.endswith('*Generated by ipynb-scrubber*\n')


def test_fence_language_is_overridable():
    """The fence is a parameter, not a baked-in assumption that notebooks are Python."""
    assert '```r\nx <- 1\n```' in render_notes({'ex-1': 'x <- 1'}, language='r')


def test_body_missing_a_trailing_newline_still_closes_its_fence():
    assert '```python\nx = 1\n```' in render_notes({'ex-1': 'x = 1'})


def test_fence_outgrows_backticks_in_the_body():
    """A cell that prints Markdown must not be able to end its own note early.

    CommonMark closes a fenced block at the first run of backticks at least as
    long as the opening fence, so a three-backtick fence around a body holding
    three backticks truncates the note and swallows the rest of the document.
    """
    content = render_notes({'ex-1': 'print("```")'}, language='python')

    assert '````python\nprint("```")\n````' in content
    assert content.endswith('*Generated by ipynb-scrubber*\n')


def test_fence_outgrows_the_longest_run_not_merely_the_first():
    content = render_notes({'ex-1': '`a`\n`````b`````\n``c``'})
    assert '``````python\n' in content


def test_each_note_is_fenced_independently():
    """One note needing a long fence does not widen the others."""
    content = render_notes({'plain': 'x = 1', 'fenced': '```'})

    assert '```python\nx = 1\n```' in content
    assert '````python\n```\n````' in content


def test_notes_survive_a_round_trip_through_a_written_file(tmp_path):
    path = tmp_path / 'notes.md'
    write(path, render_notes({'ex-1': 'x = "café ☕"'}))
    assert 'café ☕' in path.read_text(encoding='utf-8')


def test_write_creates_parent_directories(tmp_path):
    path = tmp_path / 'nested' / 'deeper' / 'notes.md'
    write(path, render_notes({'ex-1': 'x = 1'}))
    assert path.exists()


def test_write_error_surfaces_as_an_oserror(tmp_path):
    """A parent path component that is a regular file makes mkdir fail."""
    blocker = tmp_path / 'blocker'
    blocker.write_text('not a directory')

    with pytest.raises(FileExistsError):
        write(blocker / 'notes.md', render_notes({'ex-1': 'x = 1'}))


def test_a_file_that_cannot_be_moved_into_place_leaves_no_temp_file(
    tmp_path,
    failing_commit,
):
    """Content is staged beside its target and cleaned up if it cannot land."""
    with pytest.raises(OSError, match='rename failed'):
        write(tmp_path / 'notes.md', render_notes({'ex-1': 'x = 1'}))

    assert list(tmp_path.iterdir()) == []


def test_require_destination_accepts_notes_with_somewhere_to_go(tmp_path):
    require_destination(1, tmp_path / 'n.md', 'scrub-note', 'Pass --notes-file PATH.')


def test_require_destination_ignores_an_absent_destination_with_no_notes():
    """No notes means nothing to lose, so no destination is needed."""
    require_destination(0, None, 'scrub-note', 'Pass --notes-file PATH.')


def test_require_destination_states_the_fault_and_ends_with_the_remedy():
    """The message names the count and the tag, and ends with the remedy given."""
    with pytest.raises(ScrubberError) as exc_info:
        require_destination(2, None, 'my-note', 'Do the thing.')

    assert str(exc_info.value) == (
        'Found 2 cell(s) with note tag "my-note", but nowhere to save the '
        'notes. Do the thing.'
    )
