import re

from pathlib import Path

from .exceptions import MissingNotesDestinationError

#: Fence info string for notebooks that declare no kernel language.
DEFAULT_NOTE_LANGUAGE = 'python'

#: The shortest fence Markdown recognises.
MIN_FENCE = 3

_BACKTICK_RUN = re.compile(r'`+')


def _fence_for(content: str) -> str:
    """A backtick fence that ``content`` cannot terminate early.

    A noted cell is arbitrary source, and source that prints or documents
    Markdown contains backtick runs of its own. CommonMark closes a fenced block
    at the first run at least as long as the one that opened it, so a fence has
    to be longer than anything inside it or the note ends early and the rest of
    the document is swallowed as prose.
    """
    longest = max(
        (len(run.group()) for run in _BACKTICK_RUN.finditer(content)),
        default=0,
    )
    return '`' * max(MIN_FENCE, longest + 1)


def render_notes(notes_dict: dict[str, str], language: str | None = None) -> str:
    """Render collected cell notes as a Markdown document.

    Args:
        notes_dict: Map of note_id -> content.
        language: Fence info string for the note bodies, i.e. the language the
            noted cells are written in. ``None`` for a notebook that declares
            none, which falls back to :data:`DEFAULT_NOTE_LANGUAGE`.

    Returns:
        The complete notes document.
    """
    info = language or DEFAULT_NOTE_LANGUAGE
    parts = [
        '# Notebook Notes\n\n',
        'This file contains the original content of cells marked for note-taking.\n\n',
    ]

    for note_id, content in notes_dict.items():
        fence = _fence_for(content)
        parts.append(f'## {note_id}\n\n')
        parts.append(f'{fence}{info}\n')
        parts.append(content)
        if not content.endswith('\n'):
            parts.append('\n')
        parts.append(f'{fence}\n\n')

    parts.append('---\n')
    parts.append('*Generated by ipynb-scrubber*\n')

    return ''.join(parts)


def require_destination(
    note_count: int,
    destination: Path | None,
    note_tag: str,
) -> None:
    """Refuse to emit notes that have nowhere to go.

    The exercise notebook refers to each noted cell by id, so writing it without
    somewhere to put the notes leaves every one of those references dangling.
    That is one rule, enforced here rather than remembered by each front end.

    Raises:
        MissingNotesDestinationError: If notes were collected and ``destination``
            is None. The caller is expected to catch it and say how a
            destination is named where it is being called from.
    """
    if note_count and destination is None:
        raise MissingNotesDestinationError(note_count, note_tag)
