from pathlib import Path
from typing import IO

from .exceptions import ProcessingError
from .staging import write_atomic

#: Fence info string for notebooks that declare no kernel language.
DEFAULT_NOTE_LANGUAGE = 'python'


def render_notes(notes_dict: dict[str, str], language: str | None = None) -> str:
    """Render collected cell notes as a Markdown document.

    Args:
        notes_dict: Map of note_id -> content.
        language: Fence info string for the note bodies, i.e. the language the
            noted cells are written in. ``None`` for a notebook that declares
            none, which falls back to :data:`DEFAULT_NOTE_LANGUAGE`.

    Returns:
        The complete notes document.
    """
    fence = language or DEFAULT_NOTE_LANGUAGE
    parts = [
        '# Notebook Notes\n\n',
        'This file contains the original content of cells marked for note-taking.\n\n',
    ]

    for note_id, content in notes_dict.items():
        parts.append(f'## {note_id}\n\n')
        parts.append(f'```{fence}\n')
        parts.append(content)
        if not content.endswith('\n'):
            parts.append('\n')
        parts.append('```\n\n')

    parts.append('---\n')
    parts.append('*Generated by ipynb-scrubber*\n')

    return ''.join(parts)


def write_notes_file(
    notes_dict: dict[str, str],
    output_path: Path,
    language: str | None = None,
) -> None:
    """Write collected cell notes to a Markdown file.

    The file is staged beside its target and moved into place once it is
    complete, so ``output_path`` is never observed half-written.

    Args:
        notes_dict: Map of note_id -> content.
        output_path: Path where notes file will be written
        language: Fence info string for the note bodies, i.e. the language the
            noted cells are written in. ``None`` for a notebook that declares
            none, which falls back to :data:`DEFAULT_NOTE_LANGUAGE`.

    Raises:
        ProcessingError: If an error occurs while writing notes
    """
    content = render_notes(notes_dict, language)

    def write(stream: IO[str]) -> None:
        stream.write(content)

    try:
        write_atomic(output_path, write)
    except OSError as e:
        raise ProcessingError(f'Error writing notes file: {e}') from e
