from pathlib import Path

from .exceptions import ProcessingError

#: Fence info string for notebooks that declare no kernel language.
DEFAULT_NOTE_LANGUAGE = 'python'


def write_notes_file(
    notes_dict: dict[str, str],
    output_path: Path,
    language: str = DEFAULT_NOTE_LANGUAGE,
) -> None:
    """Write collected cell notes to a Markdown file.

    Args:
        notes_dict: Map of note_id -> content.
        output_path: Path where notes file will be written
        language: Fence info string for the note bodies, i.e. the notebook's
            kernel language. Defaults to :data:`DEFAULT_NOTE_LANGUAGE`.

    Raises:
        ProcessingError: If an error occurs while writing notes
    """
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with output_path.open('w') as f:
            f.write('# Notebook Notes\n\n')
            f.write(
                'This file contains the original content of cells marked '
                'for note-taking.\n\n',
            )

            for note_id, content in notes_dict.items():
                f.write(f'## {note_id}\n\n')
                f.write(f'```{language}\n')
                f.write(content)
                if not content.endswith('\n'):
                    f.write('\n')
                f.write('```\n\n')

            f.write('---\n')
            f.write('*Generated by ipynb-scrubber*\n')

    except OSError as e:
        raise ProcessingError(f'Error writing notes file: {e}') from e
