from pathlib import Path

from .actions import Note, Omit, apply, decide
from .config import ScrubbingOptions
from .exceptions import ProcessingError
from .notebook import Cell, Notebook, get_cell_source, validate_notebook

__all__ = [
    'Cell',
    'Notebook',
    'get_cell_source',
    'process_notebook',
    'validate_notebook',
]


def process_notebook(
    notebook: Notebook,
    scrub_options: ScrubbingOptions,
) -> tuple[Notebook, dict[str, tuple[str, str]]]:
    """Process a notebook to create an exercise version.

    Args:
        notebook: The input notebook to process
        scrub_options: Scrubbing options containing tags and default text

    Returns:
        Tuple of (processed_notebook, notes_dict) where notes_dict maps
        note_id -> (cell_type, original_source) for noted cells.

    Raises:
        InvalidNotebookError: If the notebook structure is invalid
        ProcessingError: If an error occurs during processing
    """
    validate_notebook(notebook)

    notes: dict[str, tuple[str, str]] = {}
    processed: list[Cell] = []

    for index, cell in enumerate(notebook.get('cells', [])):
        try:
            action = decide(cell, scrub_options)

            if isinstance(action, Omit):
                continue

            if isinstance(action, Note):
                if action.note_id in notes:
                    raise ProcessingError(
                        f"Duplicate note id '{action.note_id}'; "
                        'note ids must be unique within a notebook',
                    )
                notes[action.note_id] = (
                    cell.get('cell_type', 'code'),
                    get_cell_source(cell),
                )

            processed.append(apply(cell, action))
        except Exception as e:
            raise ProcessingError(f'Cell {index}: {e}') from e

    notebook['cells'] = processed
    metadata = notebook.get('metadata')
    if metadata is None:
        metadata = {}
        notebook['metadata'] = metadata
    metadata['exercise_version'] = True

    return notebook, notes


def write_notes_file(
    notes_dict: dict[str, tuple[str, str]],
    output_path: Path,
) -> None:
    """Write collected cell notes to a Markdown file.

    Args:
        notes_dict: Map of note_id -> (cell_type, content)
        output_path: Path where notes file will be written

    Raises:
        ProcessingError: If error occurs while writing notes
    """
    try:
        # Ensure output directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with output_path.open('w') as f:
            # Write header
            f.write('# Notebook Notes\n\n')
            f.write(
                'This file contains the original content of cells marked '
                'for note-taking.\n\n',
            )

            # Write each note
            for note_id, (cell_type, content) in notes_dict.items():
                # Write note header with human-readable ID
                f.write(f'## {note_id}\n\n')

                # Determine fence based on cell type
                if cell_type == 'code':
                    fence = '```python\n'
                elif cell_type == 'markdown':
                    fence = '```markdown\n'
                elif cell_type == 'raw':
                    fence = '```\n'
                else:
                    fence = '```\n'

                # Write content in code fence
                f.write(fence)
                f.write(content)
                # Ensure content ends with newline
                if not content.endswith('\n'):
                    f.write('\n')
                f.write('```\n\n')

            # Write footer
            f.write('---\n')
            f.write('*Generated by ipynb-scrubber*\n')

    except Exception as e:
        raise ProcessingError(f'Error writing notes file: {e}') from e
